### ISSUE TITLE
Drive vanishes after a minute after mounting

### ISSUE THREAD

**Issue by yiyangc91** [bailey27/cppcryptfs#118] opened 2021-02-04 10:47 UTC
Running cppcryptfs 1.4.35 64-bit

After mounting, drive vanishes from computer but remains "mounted" in cppcryptfs menu. See screen:

<img width="944" alt="Capture" src="https://user-images.githubusercontent.com/3031606/106881959-08df2700-6693-11eb-99cd-f5f607e8c89d.PNG">

Hitting dismount just freezes the application.

<img width="513" alt="Capture" src="https://user-images.githubusercontent.com/3031606/106882026-1d232400-6693-11eb-9d0a-5af839b981d3.PNG">

After a few moments, the application unfreezes, and nothing is dismounted.

Closing the application takes a while, I need to hit the exit button multiple times before the program realizes that nothing is actually mounted and it quits.

**Comment by yiyangc91** [comment] 2021-02-04 11:00
Did some more investigation; if I turn off "fast mount" the drive remains visible until eventually the application times out, at which point the drive is unmounted. I think for some reason here the drive is accessible while fast mount is active, but when the program internally "times out" the drive is dismounted despite everything actually working fine

**Comment by bailey27** [comment] 2021-02-07 16:57
Hi.  It sounds like you're having the same problem I had when I got my new notebook.

I submitted a fix to Dokany, and they accepted it.

https://github.com/dokan-dev/dokany/issues/957

They released a new Dokany recently https://github.com/dokan-dev/dokany/releases/tag/v1.4.1.1000

It looks like the fix is in there.  Please try it.  

I'm about to try the new Dokany myself.  

The problem wasn't 100% reproducible for me.   Generally if it happened after a reboot, it would always happen until I rebooted again.  Then it either would or wouldn't happen again until the next reboot.

Another thing to try is mounting to an empty NTFS directory instead of a drive letter.  This timeout happened only when mounting to a drive letter.

**Comment by bailey27** [comment] 2021-02-11 18:23
I haven't had the problem using the new Dokany.  Please let me know if the problem happens again for you.

**Closed by bailey27** 2021-02-11 18:23 UTC
