### ISSUE TITLE
Transfer status failing and slow speeds ontop of other virtual filesystems

### ISSUE THREAD

**Issue by blahjig** [bailey27/cppcryptfs#11] opened 2017-02-15 13:39 UTC
When running cppcryptfs on top of sshfs-win (https://github.com/billziss-gh/sshfs-win) or SFTPNetDrive (http://sftpnetdrive.com/), the windows transfer status information is not updated until the very last few seconds during a file transfer into a cppcryptfs volume running on top of one of these volumes.

Additionally the transfer speed is quite slow, approximately 2mb/s where writing directly to the sshfs volume is 20mb/s or higher, and cppcryptfs to a remote UNC volume or local disk is 20mb/s+

While the transfer is occurring the CPU does not appear to be reaching any bottlenecks, although the overall CPU rate is higher than when you simply add up all the processes CPU usage by a fairly wide margin (does that mean a large amount of CPU is being used by a driver?)

I would also like to say using sshfs + gocryptfs on linux I can achieve a little over 20mb/s on the same machine.

**Comment by bailey27** [comment] 2017-02-19 11:07
The problem could be with Dokany.

Could you try it with the mirror sample program from Dokany?

It should be installed in 

```

C:\Program Files\Dokan\Dokan Library-1.0.2\sample\mirror\mirror.exe

```

Mirror creates a pass-through virtual filesystem.  

If the problem happens with mirror, then please file a bug with Dokany.

If it doesn't, then it's a cppcryptfs problem.

Please let me know either way.

**Comment by blahjig** [comment] 2017-02-21 04:36
I'll get back to you with the results in a week

**Comment by blahjig** [comment] 2017-02-27 04:28
Hi, so infact I do not have the same problem with the dokany mirror.exe, the windows progress bar correctly updates when writing to a mirror.exe volume, and there is no speed impact.

So this must be something to do with cppcryptfs.

**Comment by bailey27** [comment] 2017-03-02 18:23
The problem with the transfer status bar not moving was happening because cppcryptfs uses one thread per filesystem.

Dokany 0.9 had problems if more than one thread was used.  So I hardcoded cppcryptfs to use one thread.  Dokany 1.02 seems to be ok.

I've added a settings tab, and you can now change the number of threads.  I tried it with 0 (in which case Dokany used 5 threads) and the progress bar moves normally.

The performance is better with more threads, but not as good as with mirror.  cppcryptfs went from taking 35 seconds with one thread to taking 25 seconds with 5 threads to copy a 100mb file to a cppcryptfs filesystem with and underlying SFTPNetDrive filesystem.

I think the remaining performance is issue is caused by the fact that whenever you write to a file, cppcryptfs queries the size of the file and reads the first few bytes.

This isn't a problem on a local filesystem.

If the file is opened without write-sharing, then cppcryptfs should be able to cache the data from the beginning of the file, and it should be able to keep track of the file size without having to query it.

It looks like windows file explorer opens the file without write-sharing.

I will work on caching the data.

I also want to point out that winfstest (https://github.com/dimov-cz/winfstest) fails on SFTPNetDrive even without mirror or cppcryptfs. It passes 149/171 of the tests instead of 171/171.

**Comment by bailey27** [comment] 2017-03-06 19:25
Another reason why it is slower is that cppcryptfs writes at most 4KB of data at a time.

Windows Explorer is doing (up to) 1MB writes when you copy file.

I will also work on buffering the output when appropriate.

**Comment by blahjig** [comment] 2017-03-10 01:20
Very interesting, I will give it another try with the new threads option next week. The buffering does sound like it would be helpful.

**Comment by bailey27** [comment] 2017-03-10 13:51
It looks like only the buffering helps.  Caching the file headers and tracking the file sizes internally made no difference.  So I have committed only the buffering changes. 

I've pushed a new version which allows the buffer size to be selected (4, 8, 16, 32, 64, 128, 256, 512 and 1024) kilobytes.

It looks like the best setup is to use threads 0 and 64KB i/o buffer.

With that setting, I see 8MB/sec transfer speeds and the transfer dialog behaves normally.

Increasing the buffer size can get the speed up to 9MB/sec, but any buffer size over 64KB results in the weird transfer dialog behavior.

I get 10MB/sec with my setup with plain sftp net drive.

Also, when I first tried to reproduce the problem, I used a 100MB file of all zeroes.  And mirror didn't show the transfer dialog problem.  

But then I realized that sftp net drive compresses the data.  So I tested with 100MB of random data instead, and mirror showed the weird transfer dialog behavior too.

With cppcryptfs, the compression doesn't help at all, because the data is already encrypted before sftp net drive sees it.

So the random data is a better test and simulates already-compressed data.

Please try it with threads 0 and 64KB buffer size and let me know if it works for you.

**Comment by blahjig** [comment] 2017-03-15 04:35
I am getting much better speeds with threads 0 and 64KB... fantastic! :-)

0 threads means 5 right? Perhaps you should just relabel that to "Default (5 threads)".

Are there any options on the command line to specify the threads and buffer size?

**Comment by bailey27** [comment] 2017-03-17 09:26
When cppcryptfs sets threads to 0, Dokany treats the 0 value to mean "use Dokany default" which is 5 threads.

I want to leave the cppcryptfs default to 1 because that's how it has been from the start.  I think labeling 0 as default would be confusing as long as cppcryptfs is really using 1 as the default.

There are no command line options about threads or buffer size, but if you run the UI and change threads to 0 and buffer size to 64KB, then that will be the settings used going forward (it saves them in the Windows registry). So if you then mount a filesystem from the command line, then those settings will be used.

**Comment by bailey27** [comment] 2017-03-23 09:21
I've done what you suggested and changed the 0 threads setting in the UI to say "Dokany default (5)".

**Closed by bailey27** 2017-03-23 09:21 UTC

**Comment by blahjig** [comment] 2017-03-29 08:47
Great! Thanks for the effort, these changes have made cppcryptfs very useful for me! :-)
