### ISSUE TITLE
Strange empty message box upon start

### ISSUE THREAD

**Issue by dhardtke** [bailey27/cppcryptfs#87] opened 2020-01-27 19:08 UTC
I am starting cppcryptfs using a shortcut to the exe in the startup folder ("shell:startup"):

> C:\tools\cppcryptfs.exe --tray

When my PC first starts I get this strange message box:

![grafik](https://user-images.githubusercontent.com/1360135/73205167-c2cabb80-4140-11ea-9cb7-eb3e633fac2e.png)

This happens since cppcryptfs 1.4.1.0 I believe.

**Comment by bailey27** [comment] 2020-01-27 22:55
I don't know what that is. 

I often use a pattern in which a function returns true on success and on failure it returns false and sets an error string to an error message to be displayed to the user.

It looks like something is returning false but leaving the error message blank and you're seeing the blank error message in the message box.

I've tried to reproduce the problem, but I haven't been able to yet.

Does cppcryptfs work after it does that when you run it?

**Comment by dhardtke** [comment] 2020-01-28 07:04
Yes, cppcryptfs works normally.

**Comment by kbh81** [comment] 2020-01-31 23:53
I have the same problem of receiving an empty message box with the new version (I skipped 1 or 2 releases over christmas though). I am calling cppcruptfs using the following shortcut from Keepass password manager: cmd://C:\[...]\cppcryptfs.exe -m H:\[...]\cfs -d s -p {PASSWORD} -t
It appears the empty message box does not appear for the first call before cppcryptfs is running but for every call after that.

**Comment by bailey27** [comment] 2020-02-02 23:30
I am able to reproduce the problem, and I've figured out where the empty message box is coming from.

I hope to make new release with the fix in the next few days.

**Comment by bailey27** [comment] 2020-02-02 23:40
Also, there was no failure return from any function when this happened.  There was a case where I was unconditionally displaying what the other instance of cppcryptfs was sending back to display to the user, even if that were nothing.

**Comment by bailey27** [comment] 2020-02-07 03:05
I've released 1.4.1.4 which has the fix for this issue https://github.com/bailey27/cppcryptfs/releases

**Closed by bailey27** 2020-02-07 03:05 UTC
