### ISSUE TITLE
Program crash if argument -m (command line) does not exist on HDD.

### ISSUE THREAD

**Issue by heikoh81** [bailey27/cppcryptfs#32] opened 2018-08-28 17:51 UTC
Hallo bailey27,

I discovered a bug if I use cppcryptfs with command line options.
I have saved the following command in KeePass:
cmd://"C:\PORTABLE\gocryptfs\cppcryptfs.exe" -m **"C:\gocryptfs_Dokumente"** -d W -p {PASSWORD}

If argument -m does not exist on disk, cppcryptfs crashes completely, in the example above: "C:\gocryptfs_Dokumente"
This is especially critical if another gocryptfs-folder is already being mounted and written to.
The error message windows give (translated from German):
"cppcryptfs does not work any more. The program is not executed properly due to a problem. The program will be closed and you will be notified, if a solution is available".

Expected behaviour:
Popup or balloon notification that path does not exist.
No crash!

My system:
Win10 1607 LTSB
cppcryptfs 1.4.0.19
Dokany 1.2.0.1000
(The problem has occured on previous versions of cppcryptfs and Dokany, also).

I hope you can fix this.
Thanks.

Best regards,
Heiko

**Comment by bailey27** [comment] 2018-08-30 00:42
Hi.  Thanks for reporting this issue.

The problem is that when you start cppcryptfs with command line arguments from a program like keepass that doesn't have an associated console, that cppcryptfs tries to print (e.g. an error message) to an invalid stderr or stdout file stream, which raises an unhandled exception.

The fix is to check the return values of OpenConsole() and also the re-opens of stderr and stdout and not to print anything if any of those fail.

I will release a new build in a couple of days with this fix.

**Comment by bailey27** [comment] 2018-09-01 15:18
Release 1.4.0.20 has the fix for this issue.

https://github.com/bailey27/cppcryptfs/releases/tag/1.4.0.20

**Closed** 2018-09-03 20:36 UTC

**Comment by heikoh81** [comment] 2018-09-04 19:08
Works now as expected.
Thank you for the fast fix.
